version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000  # Map the exposed container port to the host machine port
    volumes:
      - .:/app     # Mount the current directory to the container's working directory
